### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by Stwissel** [ktr0731/godoc-action#1]
We try to use the action like this:

```yaml
name: Publish GO documentation
on:
  workflow_dispatch:
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate GoDoc
        uses: ktr0731/godoc-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
```

But building the docker container failed:

```bash
#6 extracting sha256:16b5038bccc853e96f534bc85f4f737109ef37ad92d877b54f080a3c86b3cb3a done
#6 DONE 18.7s
#7 [2/3] RUN go get golang.org/x/tools/cmd/godoc
#7 7.282 # golang.org/x/tools/godoc/vfs
#7 7.282 /src/golang.org/x/tools/godoc/vfs/vfs.go:56:9: undefined: io.ReadAll
#7 7.465 # golang.org/x/tools/godoc/static
#7 7.465 /src/golang.org/x/tools/godoc/static/gen.go:74:13: undefined: os.ReadFile
#7 7.768 # golang.org/x/tools/internal/gocommand
#7 7.768 /src/golang.org/x/tools/internal/gocommand/invoke.go:402:62: undefined: os.ErrProcessDone
#7 ERROR: process "/bin/sh -c go get golang.org/x/tools/cmd/godoc" did not complete successfully: exit code: 2
------
 > [2/3] RUN go get golang.org/x/tools/cmd/godoc:
7.282 # golang.org/x/tools/godoc/vfs
7.282 /src/golang.org/x/tools/godoc/vfs/vfs.go:56:9: undefined: io.ReadAll
7.465 # golang.org/x/tools/godoc/static
7.465 /src/golang.org/x/tools/godoc/static/gen.go:74:13: undefined: os.ReadFile
7.768 # golang.org/x/tools/internal/gocommand
7.768 /src/golang.org/x/tools/internal/gocommand/invoke.go:402:62: undefined: os.ErrProcessDone
------
Dockerfile:4
--------------------
   2 |     
   3 |     ENV GOPATH /
   4 | >>> RUN go get golang.org/x/tools/cmd/godoc
   5 |     COPY ./main.bash /bin/main.bash
   6 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c go get golang.org/x/tools/cmd/godoc" did not complete successfully: exit code: 2
```
Any hints what we might be missing?
